Select distinct CHARACTERISTIC from AMSA_VENDORUPDATE WHERE NOTICE_STATUS = 'expired' AND WF_STATUS_ID=10 AND ID > 10203;

Select distinct CHARACTERISTIC from AMSA_VENDORUPDATE WHERE ID > 10203; 
-- WF_STATUS_ID=10 AND NOTICE_STATUS = 'expired' AND   

Select distinct CHARACTERISTIC from AMSA_VENDORUPDATE WHERE NOTICE_STATUS = 'expired' AND WF_STATUS_ID=110;

select max(id) from AMSA_VENDORUPDATE;

10203

0001157013

    SELECT ID,  DESCRIPTION, VENDOR_NO, EMAIL, CHARACTERISTIC, NOTICE_STATUS, TO_CHAR(NEW_EXPIRY_DATE, 'YYYYMMDD')  AS EXPIRY_DATE
    FROM AMSA_VENDORUPDATE
    WHERE WF_STATUS_ID IN (120);
