ALTER TABLE AMSA_RFQ_AUDIT ADD SEQUENCENO	NUMBER(10,0);

ALTER TABLE AMSA_RFQ MODIFY UPDATEDINSAP	NUMBER(3);

ALTER TABLE AMSA_RFQ_AUDIT MODIFY UPDATEDINSAP	NUMBER(3);


  CREATE TABLE "OTCS"."AMSA_RFQ_AUDIT" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"RFQNO" VARCHAR2(10 BYTE), 
	"RFQ_GROUPNO" VARCHAR2(10 BYTE), 
	"OURREF" VARCHAR2(12 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"CLOSINGDATE" DATE, 
	"VENDORNO" VARCHAR2(10 BYTE), 
	"VENDORNAME" VARCHAR2(50 BYTE), 
	"BUYERNO" VARCHAR2(3 BYTE), 
	"BUYERNAME" VARCHAR2(18 BYTE), 
	"LOCATIONNO" VARCHAR2(4 BYTE), 
	"LOCATION" VARCHAR2(50 BYTE), 
	"SCANPC" VARCHAR2(200 BYTE), 
	"SCANDATE" DATE, 
	"RETURNEDDATE" DATE, 
	"SOURCE" VARCHAR2(20 BYTE), 
	"UPDATEDINSAP" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"MATERIALNO" VARCHAR2(20 BYTE), 
	"RETFAXNO" VARCHAR2(20 BYTE), 
	"BUYEREMAIL" VARCHAR2(50 BYTE), 
	"INITIALDATE" DATE, 
	"PRICE" VARCHAR2(20 BYTE),
	"UPADATEDON" DATE DEFAULT SYSDATE
   );
   
   DROP TRIGGER TR_AMSA_RFQ_AUDIT

  CREATE SEQUENCE  "AMSA_RFQ_AUDIT_SEC"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
   
  CREATE OR REPLACE TRIGGER TR_AMSA_RFQ_AUDIT BEFORE
  UPDATE ON AMSA_RFQ FOR EACH ROW
  DECLARE
  TmpNewId Number;
  begin
    SELECT AMSA_RFQ_AUDIT_SEC.NEXTVAL
    INTO TmpNewId
    FROM Dual;
    insert into AMSA_RFQ_AUDIT 
    (
      ID
      ,RFQNO
      ,RFQ_GROUPNO
      ,OURREF
      ,DESCRIPTION
      ,CLOSINGDATE
      ,VENDORNO
      ,VENDORNAME
      ,BUYERNO
      ,BUYERNAME
      ,LOCATIONNO
      ,LOCATION
      ,SCANPC
      ,SCANDATE
      ,RETURNEDDATE
      ,SOURCE
      ,UPDATEDINSAP
      ,MATERIALNO
      ,RETFAXNO
      ,BUYEREMAIL
      ,INITIALDATE
      ,PRICE
      ,HASMULTILINES
      ,SEQUENCENO
    ) 
    VALUES
    (
      :old.ID
      ,:old.RFQNO
      ,:old.RFQ_GROUPNO
      ,:old.OURREF
      ,:old.DESCRIPTION
      ,:old.CLOSINGDATE
      ,:old.VENDORNO
      ,:old.VENDORNAME
      ,:old.BUYERNO
      ,:old.BUYERNAME
      ,:old.LOCATIONNO
      ,:old.LOCATION
      ,:old.SCANPC
      ,:old.SCANDATE
      ,:old.RETURNEDDATE
      ,:old.SOURCE
      ,:old.UPDATEDINSAP
      ,:old.MATERIALNO
      ,:old.RETFAXNO
      ,:old.BUYEREMAIL
      ,:old.INITIALDATE
      ,:old.PRICE
      ,:old.HASMULTILINES
      ,TmpNewId
    );
  end;

/
ALTER TRIGGER "OTCS"."TR_AMSA_RFQ_AUDIT" ENABLE;

  CREATE OR REPLACE FORCE VIEW VW_RFQ_AUDIT ("ID", "RFQNO", "RFQ_GROUPNO", "OURREF", "DESCRIPTION", "CLOSINGDATE", "VENDORNO", "VENDORNAME", "BUYERNO", "BUYERNAME", 
  "LOCATIONNO", "LOCATION", "SCANPC", "SCANDATE", "RETURNEDDATE", "SOURCE", "UPDATEDINSAP", "MATERIALNO", "RETFAXNO", "BUYEREMAIL", "INITIALDATE", "PRICE", 
  "UPADATEDON", "HASMULTILINES", "SEQUENCENO") AS 
  SELECT 
         AMSA_RFQ.ID
        , AMSA_RFQ.RFQNO
        , AMSA_RFQ.RFQ_GROUPNO
        , AMSA_RFQ.OURREF
        , AMSA_RFQ.DESCRIPTION
        , AMSA_RFQ.CLOSINGDATE
        , AMSA_RFQ.VENDORNO
        , AMSA_RFQ.VENDORNAME
        , AMSA_RFQ.BUYERNO
        , AMSA_RFQ.BUYERNAME
        , AMSA_RFQ.LOCATIONNO
        , AMSA_RFQ.LOCATION
        , AMSA_RFQ.SCANPC
        , AMSA_RFQ.SCANDATE
        , AMSA_RFQ.RETURNEDDATE
        , AMSA_RFQ.SOURCE
        , AMSA_RFQ.UPDATEDINSAP
        , AMSA_RFQ.MATERIALNO
        , AMSA_RFQ.RETFAXNO
        , AMSA_RFQ.BUYEREMAIL
        , AMSA_RFQ.INITIALDATE
        , AMSA_RFQ.PRICE
        , SYSDATE AS UPADATEDON
        , AMSA_RFQ.HASMULTILINES
        , 1000000000 AS SEQUENCENO
    FROM AMSA_RFQ WHERE AMSA_RFQ.RFQNO IN (SELECT A2.RFQNO FROM AMSA_RFQ_AUDIT A2)
    UNION
    SELECT  
        AMSA_RFQ_AUDIT.ID
        , AMSA_RFQ_AUDIT.RFQNO
        , AMSA_RFQ_AUDIT.RFQ_GROUPNO
        , AMSA_RFQ_AUDIT.OURREF
        , AMSA_RFQ_AUDIT.DESCRIPTION
        , AMSA_RFQ_AUDIT.CLOSINGDATE
        , AMSA_RFQ_AUDIT.VENDORNO
        , AMSA_RFQ_AUDIT.VENDORNAME
        , AMSA_RFQ_AUDIT.BUYERNO
        , AMSA_RFQ_AUDIT.BUYERNAME
        , AMSA_RFQ_AUDIT.LOCATIONNO
        , AMSA_RFQ_AUDIT.LOCATION
        , AMSA_RFQ_AUDIT.SCANPC
        , AMSA_RFQ_AUDIT.SCANDATE
        , AMSA_RFQ_AUDIT.RETURNEDDATE
        , AMSA_RFQ_AUDIT.SOURCE
        , AMSA_RFQ_AUDIT.UPDATEDINSAP
        , AMSA_RFQ_AUDIT.MATERIALNO
        , AMSA_RFQ_AUDIT.RETFAXNO
        , AMSA_RFQ_AUDIT.BUYEREMAIL
        , AMSA_RFQ_AUDIT.INITIALDATE
        , AMSA_RFQ_AUDIT.PRICE
        , AMSA_RFQ_AUDIT.UPADATEDON
        , AMSA_RFQ_AUDIT.HASMULTILINES
        , AMSA_RFQ_AUDIT.SEQUENCENO
--        , NVL(AMSA_RFQ_AUDIT.SEQUENCENO,1) AS SEQUENCENO
     FROM AMSA_RFQ_AUDIT;
 
