ALTER TABLE AMSA_RFQ MODIFY VENDORNAME  VARCHAR2(50);
ALTER TABLE AMSA_RFQ MODIFY LOCATION   	VARCHAR2(50);

ALTER TABLE AMSA_RFQ ADD MATERIALNO   	VARCHAR2(100);  -- EMATN
ALTER TABLE AMSA_RFQ ADD RETFAXNO   	VARCHAR2(20);

ALTER TABLE AMSA_RFQ ADD MATERIALDESC	VARCHAR2(100);  -- MAKTX 

ALTER TABLE AMSA_RFQ MODIFY MATERIALNO	VARCHAR2(20);

ALTER TABLE AMSA_RFQ ADD BUYEREMAIL	VARCHAR2(50);  -- SMTP_ADDR

ALTER TABLE AMSA_RFQ ADD INITIALDATE DATE;

ALTER TABLE AMSA_RFQ ADD PRICE	VARCHAR2(20);

COMMIT;

select CLOSINGDATE, CONCAT(CONCAT('D/', TO_CHAR(CLOSINGDATE, 'YYYY/MM/DD')),':0:0:0') AS CSDATE from AMSA_RFQ where INITIALDATE is not null;

AMSA_CS_GENERIC_INT_U

    SELECT substr(ci.REGIONNAME, (INSTRC(ci.REGIONNAME,'_',1,2)+1)) 
    FROM CATREGIONMAP ci
    WHERE ci.CATNAME = 'RFQ Responses'
    AND ci.AttrName = 'Closing Date';

SELECT DATAID FROM DTREECORE WHERE NAME = '1001638185-6019855524-WIDE RANGE ENGINEERING CC' AND OWNERID=-2000;  -- OR SHOULD IT BE DTREE?

        SELECT SEGMENTBLOB FROM LLATTRBLOBDATA WHERE ID = 7971620 AND VERNUM = (SELECT MAX(VERNUM) FROM LLATTRBLOBDATA WHERE ID = 7971620 );
        SELECT '=' || Str_AttribNo || ',' INTO Str_Search FROM DUAL;
        SELECT INSTR(Str_Value, Str_Search) INTO Num_Pos FROM DUAL;
        SELECT SUBSTR(Str_Value, 0, INSTR(Str_Value, '{', Num_Pos)) INTO Str_Value_Start FROM DUAL;
        SELECT INSTR(Str_Value, '}', Num_Pos) INTO Num_Val_End FROM DUAL;
        SELECT SUBSTR(Str_Value, Num_Val_End, (LENGTH(Str_Value)-Num_Val_End +1)) INTO Str_Value_End FROM DUAL;
        SELECT Str_Value_Start || v_Value || Str_Value_End INTO Str_New_Value FROM DUAL;


create or replace PROCEDURE P_NEWSAPLINK_RFQ_PREP AS 
BEGIN
  
  INSERT INTO AMSA_SAPLINK (DATAID,
OBJECT_ID,
CLASSNAME,
FIELD_NAME,
REC_ID,
VER_ID,
VER_DATE,
DOCNAME,
DOCID,
ARCHID, 
DESCRIPTION,
MIMETYPE,
STATUS_F,
ACTION,
INFO_TYPE,
SUB_INFO_TYPE,
SAP_OBJTYPE,
SAP_DOCTYPE
) 
( SELECT  distinct(ll.ID) AS DATAID
    ,ll.ValStr AS OBJECT_ID
    ,c.CLASSNAME AS CLASSNAME
    ,ci.ATTRNAME AS FIELD_NAME
 ,dv.DocID|| '_'||dv.Version AS REC_ID
 ,dv.Version AS VER_ID
 ,dv.VerCDate AS VER_DATE
 ,dv.Filename AS DOCNAME
 ,DBMS_LOB.SUBSTR(p.providerdata, ((INSTR(p.providerdata,',',(INSTR(p.providerdata,'@')))-2)-(INSTR(p.providerdata,'@'))), (INSTR(p.providerdata,'@')+1)) AS DOCID 
 ,DBMS_LOB.SUBSTR(p.providerdata,2,(instr(p.providerdata,'//',1,1))+2) AS ARCHID
 ,NULL
 ,'PDF'
 ,'N'
 ,'N'
 ,C.INFO_TYPE AS INFO_TYPE
 ,C.SUB_INFO_TYPE as SUB_INFO_TYPE
 ,C.SAP_OBJTYPE as SAP_OBJTYPE
 ,C.SAP_DOCTYPE as SAP_DOCTYPE
  FROM DVersData dv
  ,PROVIDERDATA p
  ,LLATTRDATA ll
  ,CATREGIONMAP ci
  ,AMSA_SAPLINK_CAT c
  ,AMSA_RFQ rfq
  where dv.ProviderId = p.providerID 
  and rfq.RFQNO = ll.ValStr
  --and (rfq.CLOSINGDATE >= (sysdate - 3) 
  and rfq.CLOSINGDATE <= sysdate
  and ci.CATNAME = C.CATNAME
  and p.providerType = 'L1'
  and dv.VERTYPE is null
  and dv.DocID = ll.ID
  and  ll.DefID = ci.CatID
    and ll.AttrID = substr(ci.REGIONNAME, (INSTRC(ci.REGIONNAME,'_',1,2)+1))
    and LENGTH(ll.ValStr) > 2
    and ci.CATNAME in ('RFQ Responses')
      and ci.AttrName in ('RFQ Number')     
       and dv.DocID|| '_'||dv.Version NOT IN (select REC_ID FROM AMSA_SAPLINK WHERE CLASSNAME = 'RFQS'));

COMMIT;


UPDATE AMSA_SAPLINK
SET DESCRIPTION = (SELECT NAME from DTREECORE
where DTREECORE.dataid = AMSA_SAPLINK.dataid);

COMMIT;
  
END P_NEWSAPLINK_RFQ_PREP;

