ALTER TABLE AMSA_RFQ MODIFY VENDORNAME  VARCHAR2(50);
ALTER TABLE AMSA_RFQ MODIFY LOCATION   	VARCHAR2(50);

ALTER TABLE AMSA_RFQ ADD MATERIALNO   	VARCHAR2(100);  -- EMATN
ALTER TABLE AMSA_RFQ ADD RETFAXNO   	VARCHAR2(20);

ALTER TABLE AMSA_RFQ ADD MATERIALDESC	VARCHAR2(100);  -- MAKTX 

ALTER TABLE AMSA_RFQ MODIFY MATERIALNO	VARCHAR2(20);

ALTER TABLE AMSA_RFQ ADD BUYEREMAIL	VARCHAR2(50);  -- SMTP_ADDR

COMMIT;

"6218012468"
