create or replace PROCEDURE CleanupRFQ
IS
BEGIN
    UPDATE AMSA_RFQ SET UPDATEDINSAP = 80 WHERE RFQNO IN (SELECT RFQNO FROM AMSA_RFQ WHERE UPDATEDINSAP IN (1,2) AND PRICE IS NULL  and ClosingDate > sysdate - 90);
    UPDATE AMSA_SAPLINK SET STATUS_F = 'E' WHERE CLASSNAME = 'RFQS' AND  STATUS_F = 'N' AND OBJECT_ID IN (SELECT RFQNO FROM AMSA_RFQ WHERE UPDATEDINSAP IN (1,2) AND PRICE IS NULL  and ClosingDate > sysdate - 90);
    COMMIT;
END;