DROP TABLE OTCS.AMSA_VENDOR_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE OTCS.AMSA_VENDOR_DETAIL
(
  ID                      NUMBER(10)               NOT NULL,
  VENDOR_NO       VARCHAR2(50 BYTE), --VENDOR_NO
  CERTFICATE       VARCHAR2(50 BYTE), --CERTIICATE
  VENDOR_NAME   VARCHAR2(50 BYTE), --VENDOR_NAME
  STATUS              VARCHAR2(20 BYTE), --STATUS
  EMAIL                 VARCHAR2(50 BYTE), --EMAIL
  EXPIRY_DATE      VARCHAR2(50 BYTE) --EXPIRY_DATE
);

CREATE SEQUENCE  "OTCS"."AMSA_VENDOR_DETAIL_SEC"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE OR REPLACE PROCEDURE OTCS.AMSA_VENDOR_DETAIL_U
                   (v_VENDOR_NO     IN NVARCHAR2
                   ,v_CERTIFICATE    IN NVARCHAR2
                   ,v_VENDORNAME   IN NVARCHAR2
                   ,v_STATUS           IN NVARCHAR2
                   ,v_EMAIL              IN NVARCHAR2
                   ,v_EXPIRYDATE     IN NVARCHAR2)
AS
TmpNewId Number;
TmpRecExist Number;
BEGIN
            SELECT AMSA_VENDOR_DETAIL_SEC.NEXTVAL
            INTO TmpNewId
            FROM Dual;
            INSERT INTO AMSA_VENDOR_DETAIL ("ID", VENDOR_NO, CERTFICATE, VENDOR_NAME, STATUS, EMAIL, EXPIRY_DATE)
            VALUES (TmpNewId, v_VENDOR_NO, v_CERTIFICATE, v_VENDORNAME, v_STATUS, v_EMAIL, v_EXPIRYDATE);
  COMMIT;
END;
/
